[2024-11-14T05:49:20.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T05:49:20.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T05:48:57.209181+00:00 [queued]>
[2024-11-14T05:49:20.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T05:48:57.209181+00:00 [queued]>
[2024-11-14T05:49:20.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T05:49:20.379+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-14 05:48:57.209181+00:00
[2024-11-14T05:49:20.387+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-14T05:48:57.209181+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp0q4glud7']
[2024-11-14T05:49:20.390+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4092) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T05:49:20.391+0000] {standard_task_runner.py:91} INFO - Job 171: Subtask dbt_test
[2024-11-14T05:49:20.391+0000] {standard_task_runner.py:63} INFO - Started process 4093 to run task
[2024-11-14T05:49:20.446+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-14T05:48:57.209181+00:00 [running]> on host 5c9ef59c8996
[2024-11-14T05:49:20.548+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T05:48:57.209181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T05:48:57.209181+00:00'
[2024-11-14T05:49:20.549+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T05:49:20.567+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T05:49:20.568+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-14T05:49:20.590+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T05:49:22.723+0000] {subprocess.py:93} INFO - [0m05:49:22  Running with dbt=1.8.7
[2024-11-14T05:49:23.773+0000] {subprocess.py:93} INFO - [0m05:49:23  Registered adapter: snowflake=1.8.4
[2024-11-14T05:49:24.237+0000] {subprocess.py:93} INFO - [0m05:49:24  Found 2 models, 1 source, 459 macros
[2024-11-14T05:49:24.242+0000] {subprocess.py:93} INFO - [0m05:49:24
[2024-11-14T05:49:24.243+0000] {subprocess.py:93} INFO - [0m05:49:24  Nothing to do. Try checking your model configs and model specification args
[2024-11-14T05:49:25.111+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-14T05:49:25.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T05:49:25.141+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-14T05:48:57.209181+00:00, execution_date=20241114T054857, start_date=20241114T054920, end_date=20241114T054925
[2024-11-14T05:49:25.185+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-14T05:49:25.204+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-14T05:49:25.210+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
